# -*- coding: utf-8 -*-
"""hi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sqeolKBIKoFpvmTL34di-QUiePU_zwty
"""

print('hi')